language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "pip install -r requirements-testing.txt"
  - "python setup install"

script:
  - /usr/bin/env bash test.sh
  - /usr/bin/env python tests/test_treelib.py
  - /usr/bin/env python tests/test_plugins.py
