language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "python setup.py install"

script:
  - /usr/bin/env python tests/test_treelib.py
  - /usr/bin/env python tests/test_plugins.py
